### ISSUE TITLE
Could you please upload the dataset

### ISSUE THREAD

**Issue by cxh981212** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#11]
Could you please upload the dataset:"DiDi Chuxing GAIA Open Dataset Initiative", (like gps_20161116.csv), which is needed in "process_trajectories.py". The website "https://outreach.didichuxing.com/research/opendata/en/" is not availabe now. Thank you.

**Comment by neardws** [comment]
Certainly, please refer to the [repository](https://github.com/neardws/Vehicular-Trajectories-Processing-for-Didi-Open-Data) for more information.

**Comment by cxh981212** [comment]
Got it, thank you!
