### ISSUE TITLE
Single GPU Environment Support

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#12]
hello,I want to know if Idon`t have two GPU,can I run it?

**Comment by neardws** [comment]
If you want to run the experiment on a single GPU, you can modify the settings in the following code block from the [experiment.py](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/Experiment/experiment.py) file located in the /Experiment folder of the GitHub repository:

```python
gpus = tf.config.experimental.list_physical_devices('GPU')
memory_limit = 4 * 1024
tf.config.experimental.set_virtual_device_configuration(gpus[0], 
    [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=memory_limit)])
```
In the code above, the gpus variable lists all the available GPUs on the system, and the memory_limit variable sets the amount of memory allocated to the virtual device configuration for the first GPU. By default, the code uses the first GPU in the list (gpus[0]). If you have a different GPU you'd like to use, you can change this value accordingly.

Note that the second GPU is commented out by default, but you can uncomment the relevant line and modify the memory limit to allocate memory to that GPU as well, if desired.

Once you've made the necessary changes, save the file and run the experiment again.

**Comment by wyt675** [comment]
Thank you! And I want to konw if the CPU only can support it?

**Comment by neardws** [comment]
I haven't tried it, but you're welcome to give it a go and see what you find out.

**Comment by wyt675** [comment]
ok,Thank you very much
