### ISSUE TITLE
通过yml文件创建环境

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#13]
![截图1680770990](https://user-images.githubusercontent.com/83149125/230328218-9976a20a-c590-4491-84f7-4e73df24c468.png)

**Comment by wyt675** [comment]
<img width="627" alt="77d1eefcc2928c2cbbe6eee0abb74de" src="https://user-images.githubusercontent.com/83149125/230328835-82d76d62-17b9-477a-962e-9d30ebbad52c.png">

**Comment by neardws** [comment]
可以先换个源试试

**Comment by y245960175** [comment]
![image](https://user-images.githubusercontent.com/83193242/230527879-6c3e89f1-4b08-4bc0-9ddb-0e68da0da767.png)
请问acme中找不到types 怎么处理呢 ？

**Comment by neardws** [comment]
> ![image](https://user-images.githubusercontent.com/83193242/230527879-6c3e89f1-4b08-4bc0-9ddb-0e68da0da767.png)
> 请问acme中找不到types 怎么处理呢 ？

请确认一下安装的版本是否正确，是否为dm-acme==0.4.0

**Comment by y245960175** [comment]
好的谢谢

**Comment by wyt675** [comment]
![屏幕截图 2023-04-08 163652](https://user-images.githubusercontent.com/83149125/230712208-eb880cd9-fd65-4bd9-8b97-267880e674a6.png)
请问导入yml文件出现这样的错误怎么解决呀

**Comment by neardws** [comment]
> ![屏幕截图 2023-04-08 163652](https://user-images.githubusercontent.com/83149125/230712208-eb880cd9-fd65-4bd9-8b97-267880e674a6.png)
> 请问导入yml文件出现这样的错误怎么解决呀

这个报错感觉是不是你这边网络环境的问题啊，可以考虑换个网络环境试试

**Comment by wyt675** [comment]
谢谢，解决了，我一个库一个库下载的，应该就是网络问题
