### ISSUE TITLE
E: Unable to locate package libpython3.9

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#14]
![屏幕截图 2023-04-08 163652](https://user-images.githubusercontent.com/83149125/230761513-54f02383-3dcb-4d6a-898c-bfb787386c9f.png)
你好，请问使用sudo apt-get install libpython3.9仍旧报错是什么问题呢，谢谢谢谢

**Comment by wyt675** [comment]
![屏幕截图 2023-04-09 160541](https://user-images.githubusercontent.com/83149125/230761614-49e0dca9-36e0-427f-a7f8-380fadd551ea.png)
对不起，上面的图片发错了

**Comment by neardws** [comment]
先运行下面的命令，再试试。
```bash 
sudo apt-get update
```
