### ISSUE TITLE
code help

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#16]
您好，我正在学习代码，想请教一个问题。就是先有了任务卸载的决策，然后进行通信资源分配，然后还有完成有线传输后，才能进行计算任务。但是假设任务k在时隙t要卸载到边缘节点e上，t时隙分配给k的通信资源为0，所以上传时延为punish_time，还要加上任务的有线传输时延，但是如果节点e又存在可用的计算资源分配，计算时延可以计算出来，但是对于边缘节点e来说，被这个车辆占用的资源持续时隙occupied_time在代码中写的是从卸载的时隙t开始到计算完成的时隙，但是不是还存在任务上传和卸载的时延吗？

**Comment by neardws** [comment]
您好，感谢提出这个问题，可以看出 Code Review 非常仔细，您提的问题非常重要。理论上确实是这样的，但是考虑到车辆和边缘节点是独立做决策，同时，在代码实现的细节中，需要考虑时隙间的同步问题，会对整体进行相应的简化。

**Comment by wyt675** [comment]
好的，谢谢！

**Comment by wyt675** [comment]
您好，我想请教一下一个关于动作的问题，就是actor的输出是（x,x,x,x,......)，其中是包含27位，但是后面说是将其reshape成了3*9的矩阵，然后选择根据每一行的最大值作为处理节点，也就是每一行应该是（0，0，0，0，1，0，0，0，0）这样的，我想问一下这个是怎么由（x,x,x,....)这样的变成（0，0，0，0，1，0，0，0，0，0，0，0，1，0，0，0，0，0，0，0，0，0，1，0，0，0，0）这样的27维向量中每九个存在一个最大值的呢？不知道我的理解对不对，希望您帮我解决一下

**Comment by neardws** [comment]
其实不需要从（x,x,x,x,......)转变到（0，0，0，0，1，0，0，0，0），只需要reshape之后，把每一行的最大值取出来即可。实际来说，因为只需要得到下标，即第几个边缘节点来处理，所以可以直接使用```argmax()```函数。
