### ISSUE TITLE
博主能不能讲一下代码结构啊，能力不够看不太懂

### ISSUE THREAD

**Issue by 921zzz** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#17]

**Comment by neardws** [comment]
项目结构在https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning#readme的File Structure中写了，不清楚这个代码结构是指什么？

**Comment by 921zzz** [comment]
您好，很抱歉，就是我看不太懂文章中所提到的任务卸载，资源分配的具体结构以及两者之间的联合优化这样的一个结构，对代码的一个实现过程不太清楚。

**Comment by neardws** [comment]
数据集的处理可以参考另外一个项目https://github.com/neardws/Vehicular-Trajectories-Processing-for-Didi-Open-Data

**Comment by neardws** [comment]
关于数据集处理的相关信息也可以参考#20

**Comment by 670555467** [comment]
> 关于数据集处理的相关信息也可以参考#20



> <img alt="CleanShot 2023-05-11 at 19 42 40@2x" width="799" src="https://private-user-images.githubusercontent.com/23012163/237675874-facacf28-64db-44e3-9fb7-a04ce5b94759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTM5NzIsIm5iZiI6MTcwNTExMzY3MiwicGF0aCI6Ii8yMzAxMjE2My8yMzc2NzU4NzQtZmFjYWNmMjgtNjRkYi00NGUzLTlmYjctYTA0Y2U1Yjk0NzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAyNDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNGE4MTIyY2YyMDk0MjU3Zjk1N2I1NGFlOTFlZDEwNTNhNTAzOTYxMmY1ZmJiODJiZjA2ZDRkZjQzNWM3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98eErCQU0HOQj3akwwotL8Syy0uRQU69LbdJg4Hyej8">
> * 首先，task offloading 和 resource allocation 分别通过MAD4PG 和凸优化来确定。
> * 当然，MAD4PG 的训练是通过 agent 和环境进行交互来实现的，所以当 agent 做出了 action（task offloading）之后，再通过 gradient-based iterative method 和 KKT condition 得到传输功率和计算资源的分配方案。
> * 所以，在代码实现中，基于 gradient-based iterative method 和 KKT condition 的算法是在 MAD4PG 中的环境中实现，即 agent 的 action 传入到环境中后，环境再得到一个整体的 action（任务卸载、传输功率分配，以及计算资源分配），最后就可以得到一个 reward 作为反馈。

你好，在计算资源分配的过程中，没有看到拉格朗日乘子具体是怎么优化的呢
