### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by ttctiong** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#19]
![Deprecation v8](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/assets/79743447/3fa1aec4-1b87-4fe3-889a-9acd976a044f)

**Comment by joiln** [comment]
运行experiment.py，并在main函数里面修改要运行的算法，比如maddpg、mad4pg等
