### ISSUE TITLE
No module named "acme.types" issue

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#2]
hello,I want to konw why I have the wrong"No module named 'acme.types'",but I can't solve it,it will be wrong
"ERROR: Could not find a version that satisfies the requirement acme_types (from versions: none)
ERROR: No matching distribution found for acme_types".thank you

**Comment by neardws** [comment]
The issue can be fixed by installing the module acme as follows.

```pip install dm-acme```

**Comment by neardws** [comment]
The conda environment file is located in environment.yml.
It can be used to create the environment by:

```conda env create -f environment.yml```
