### ISSUE TITLE
请求仿真实验代码的一些疑惑解答

### ISSUE THREAD

**Issue by joiln** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#20]
您好，非常感学您开源如此优秀的代码提供给我们学习，我是做UAV对固定物联网设备任务卸载的，想学习您的代码和思想，并形成自己的仿真环境和实验，但是由于能力有限，看代码有很多的疑惑，若能解释一下不胜感激。
1. vehicle的trajectories_file_name，具体的数据结构是如何，是怎么封装的

2. 在代码reaed_vehicle_trajectories中new_df = df[df['vehicle_id'] == vehicle_id]获取到对应vehicle_id的所有数据，型获取longitude和latitude列中的最大值与最小值，那么在计算max(min) distance 是否是错误的，因为获取到的(x,y)不是一个时间下的坐标。

3. 在代码reaed_vehicle_trajectories中最大距离和最小距离计算时减去的是edge的通信范围吗，最大最小距离是到原点的距离吗？

4. self._vehicle_number_in_edge = int(self._vehicle_number / self._edge_number)指的是什么，vehicle与edge的比值吗，还是指的在t时刻下edge e内有x个vehicle

5. 问题4中self._vehicle_number_in_edge与environment.py中vehicle_index_within_edges是不是同一个意思

6. environment.py与make_environment.py有什么区别吗，它们的作用是什么

**Comment by neardws** [comment]
感谢关注，非常乐意为你解答。

1. 车辆轨迹相关的信息请参考另外一个项目https://github.com/neardws/Vehicular-Trajectories-Processing-for-Didi-Open-Data
2. 应该是没有问题的，因为车辆轨迹在处理的时候已经按照时间片进行填充（如果有数据缺失的话），同时，获取到的x,y坐标是可以确保是同一时间片的。
3. 对的，在read_vehicle_trajectories中减去的self._communication_range是指edge的通信范围，这里的最大最小距离应该是指针对目前这个边缘节点来说的，我现在记得不是很清楚，可以参考看看https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/Environment/utilities.py ，大体思路应该是先把整个地图划分成9块，每块中有一个边缘节点，然后在找在单个边缘节点覆盖范围内的车辆。
4. self._vehicle_number_in_edge是一个数量，即期望有多少车，因为后面筛选出的车辆希望尽量都在边缘覆盖范围内，同时希望筛选出的车辆需要满足这个数量。
5. 不是的，https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/Environment/environment.py 中的vehicle_index_within_edges是指边缘节点覆盖范围内车辆的ID。
6. [environment.py](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/Environment/environment.py) 是定义强化学习中的环境，而 [make_environment.py](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/Experiment/make_environment.py) 的作用是使用设定的值，实际地把这个环境对象给新建出来，并进行保存，以便在不同的对比算法中使用相同环境进行仿真实验。

**Comment by yummyZy** [comment]
博主今年毕业嘛，非常感谢您的代码开源，我的研究方向也刚好是这个。祝您毕业快乐！！！

**Comment by neardws** [comment]
感谢，特别巧的是，今天下午刚答辩完，😄

**Comment by yummyZy** [comment]
> 

那就祝您毕业快乐啦，我的说是方向刚好是您这篇论文的方向，本来还在一筹莫展毕业的问题，您的代码对我收获太大啦，真的非常感谢您！前路漫漫亦灿灿！！！

**Comment by lwc6666** [comment]
> > 
> 
> 那就祝您毕业快乐啦，我的说是方向刚好是您这篇论文的方向，本来还在一筹莫展毕业的问题，您的代码对我收获太大啦，真的非常感谢您！前路漫漫亦灿灿！！！

您好学长/学姐，我目前也对毕业一筹莫展TAT ，想向您请教一些问题可以吗....方便留一个联系方式吗，我加您
