### ISSUE TITLE
博主我想问您一下您论文中的VEC架构的图是怎么画的呀，能教一下方法嘛

### ISSUE THREAD

**Issue by yummyZy** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#21]
博主你论文里面VEC架构图是用什么画的哇能教一下方法嘛

**Comment by neardws** [comment]
你好，是使用[亿图图示](https://www.edrawsoft.cn/edrawmax/)画的，亿图图示是一款国产软件哦，欢迎支持！

**Comment by yummyZy** [comment]
博主，最近有想读博的想法能向您咨询一下嘛。给您主页的邮箱发邮件可以嘛

**Comment by neardws** [comment]
好呀，欢迎👏

**Comment by yummyZy** [comment]
学长我发您邮箱了，麻烦您看一下。感谢学长的回答！！😭
