### ISSUE TITLE
请教一下作者关于mad4pg的实验问题

### ISSUE THREAD

**Issue by Simple11024** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#23]
**Describe the bug**

**To Reproduce**
2. ...
3. See error

**Expected behavior**

**Screenshots**

**Runtime Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Python Version [e.g. 3.11.2]
 - ...

**Additional context**

**Comment by Simple11024** [comment]
作者大大，您好，我是一名在读研究生，有幸读到您的论文。我最近在学习您的代码。您的代码整洁美观，可读性极高；论文写得也非常好，让我收获很多。遇到一些问题，希望得到您的指点，感激不尽。
1.environment_old和environment的主要区别 我尝试使用mad4pg调用environment也能跑 您能指点一下吗 
2.我是在win10的虚拟机上运行的，纯cpu跑，跑一轮madd4g的时间是6h，请问如果用gpu训练的话，速度能达到多少（如果速度提升大我想试试用gpu跑跑试试）
3.我的mad4pg跑5h就会不正常终止，导致cumulative reward 只有500个数据，无法画出完整的图（您论文中完整的应该为4000个数据是正常的）但是我看到您的Draw/draw_result.ipynb中示例图中的cumulative reward也只有700个数据，但是在figure/draw_cumulative_reward.ipynb中mad4pg的cumulative reward拥有4000个数据 我想请您指点一下

**Comment by neardws** [comment]
1. environment是最新的版本，用这个就行
2. 使用GPU的话（NVIDIA 3090），一轮（4000 iterations）好像是半天吧，记不太清楚了
3. draw_result.ipynb 里的数据并不是对应算法收敛图，因为所有原始数据其实都是保存在 /用户名/acme/ 文件夹下的。至于跑 5h 就终止，你需要看看它是否迭代到了你设置的iterations，如果没有，它有什么报错信息吗？

**Comment by Simple11024** [comment]
感谢您的回复，我的问题都已经解决了，感谢！
