### ISSUE TITLE
执行DDPG算法时报错：valueerror: typeerror: object of type 'discretevalueddistribution' has no len() 

### ISSUE THREAD

**Issue by Jadaeu** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#26]
![image](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/assets/105416501/2348ba62-6d5f-43dc-add7-0ebaf776fd46)

**Comment by Jadaeu** [comment]
能够正常执行d4pg、maddpg、mad4pg算法，但是在执行ddpg算法时报上面的错，网上搜了好久，自己也去报错信息提示的文件里找个找，都没有找到问题所在，求好心大佬解答一下。

**Comment by gml576369** [comment]
您好，请问这个问题是怎么解决的啊，我也遇到一样的问题了

**Comment by gml576369** [comment]
> 您好，请问这个问题是怎么解决的啊，我也遇到一样的问题了，求大佬解答0.0

**Comment by gml576369** [comment]
您好，请问这个问题是怎么解决的啊，我也遇到一样的问题了，求大佬解答0.0

**Comment by NNNNelson** [comment]
请问你们解决了这个问题了吗，我也遇到了
