### ISSUE TITLE
请问作者我改动了环境，是不是得通过make_environment.py文件创建新的pkl文件？但是我看文件里没有下面源码对应的trajectories_file。。

### ISSUE THREAD

**Issue by Jadaeu** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#27]
![image](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/assets/105416501/1234b0ca-7e85-4a90-b07a-1b93bba4aed3)

**Comment by sobhankazemi** [comment]
Hi i don't know if this helps right now or not but you need to create a CSV folder in  project root directory and copy didi dataset in it (gps_20161116) .
Finally you need to run experiment/process_trajectories.py and all .csv files will be generated

**Comment by NNNNelson** [comment]
怎样可以得到didi的数据集，我在博主提供的连接中获得不到

**Comment by Jadaeu** [comment]
> 怎样可以得到didi的数据集，我在博主提供的连接中获得不到

给我你的邮箱吧，我发你

**Comment by NNNNelson** [comment]
我的邮箱：2196349672@qq.com  太感谢你了

**Comment by lwc6666** [comment]
> > 怎样可以得到didi的数据集，我在博主提供的连接中获得不到
> 
> 给我你的邮箱吧，我发你

哥您好，可以也发我一份数据集吗 1076450887@qq.com

**Comment by SuperLuckyStar666** [comment]
楼主您好，请问这篇论文的Table 1中 𝑙𝑒（ Location of edge node 𝑒）的值是如何设置的呢？用的是数据集中的数据吗？我在代码中没找到边缘节点位置值设置的这个代码。
