### ISSUE TITLE
Windows运行环境

### ISSUE THREAD

**Issue by wyt675** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#3]
你好，我还想问一下这个可以在windows上面跑吗？我配置yml文件，也出现很多库下载不了的问题“Could not find a version that satisfies the requirement absl (from versions:），这个原因是因为我没在linux下面运行程序吗

**Comment by neardws** [comment]
应该是的，建议使用ubuntu，如果没有的话，也可以考虑使用Windows下的 Windows Subsystem for Linux [(WSL) 子系统](https://learn.microsoft.com/zh-cn/windows/wsl/about).

**Comment by wyt675** [comment]
好的好的，谢谢！
