### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by xlq246860** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#4]
请问原始数据集是什么呀？包括task，vehicle，edge等信息封装成的pkl文件，如果想改动代码的environment的话，请问是需要重构数据集吗？

**Comment by neardws** [comment]
你好，本项目中task，vehicle, and edge等对象的相关设置是通过随机生成的（具有固定随机式种子饼服从某分布或单纯区间内随机，相关代码请参见 [Environment/dataStruct.py](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/9e8a20bed46fabf55e13d5c08fcae0a6e6c9450a/Environment/dataStruct.py)），具体设置可参考下表。
<img width="631" alt="WechatIMG364" src="https://user-images.githubusercontent.com/23012163/217988998-bc405c1c-12fb-4c6e-a2e2-8dfe48ead119.png">

另外，车辆轨迹信息是来自于Didi GAIA Open Data Set, 相关处理代码可参考 https://github.com/neardws/Vehicular-Trajectories-Processing-for-Didi-Open-Data

**Comment by neardws** [comment]
如果改动Environment, 那么上述相关数据自然需要重新更新，或者说环境中变量，比如Agent的观测是和这些数据定义是息息相关的。所以，如果有改动Environment的需求，建议可以从底层这些数据配置改起。

**Comment by SuperLuckyStar666** [comment]
楼主您好，请问这篇论文的Table 1中 𝑙𝑒（ Location of edge node 𝑒）的值是如何设置的呢？用的是数据集中的数据吗？我在代码中没找到边缘节点位置值设置的这个代码。
