### ISSUE TITLE
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ttctiong** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#5]
![Libpython3 9 so 1 0](https://user-images.githubusercontent.com/79743447/224319929-145338de-1041-4171-856e-cda4d794d8bc.jpg)

**Comment by ttctiong** [comment]
libpython3.9.so.1.0: cannot open shared object file: No such file or directory 

![Libpython3 9 so 1 0 v2](https://user-images.githubusercontent.com/79743447/224469180-6ae8f6b1-144f-4462-9b3c-b7ddbf01ad2a.JPG)

**Comment by neardws** [comment]
Try this:

```bash
sudo apt-get install libpython3.9
```

By referring https://stackoverflow.com/questions/62945126/importerror-libpython3-7m-so-1-0-cannot-open-shared-object-file-no-such-file
