### ISSUE TITLE
ModuleNotFoundError: No module named 'Log'

### ISSUE THREAD

**Issue by ttctiong** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#6]
![ModuleNotFoundError  No module named 'Log'](https://user-images.githubusercontent.com/79743447/224490195-267205a8-60aa-475b-b34a-074a74dac4f4.JPG)

**Comment by neardws** [comment]
> ![ModuleNotFoundError  No module named 'Log'](https://user-images.githubusercontent.com/79743447/224490195-267205a8-60aa-475b-b34a-074a74dac4f4.JPG)
> 
> 

The "Log" module is defined in /Log. So I suggest you should run it in the root directory. Or use an IDE, such as VS Code, to open the root directory.
