### ISSUE TITLE
libserialization_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

### ISSUE THREAD

**Issue by jin521-qing** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#8]
![image](https://user-images.githubusercontent.com/65586512/229057103-8bce57ca-e438-458d-b16f-1601bae99952.png)
您好，请问这个问题是因为啥？我查到可能是版本问题，我安装了protobuf3.17.2 ,也不可以，请问您使用的是啥版本？或许有其他解决办法吗？非常感谢🙇‍

**Comment by neardws** [comment]
这样描述我也不是很清楚呢，之前还没出现过相关问题，能不能描述一下你的运行环境呢？感觉有可能是运行环境中缺少文件。

**Comment by neardws** [comment]
> 这样描述我也不是很清楚呢，之前还没出现过相关问题，能不能描述一下你的运行环境呢？感觉有可能是运行环境中缺少文件。

也可以先看看以前的issues

**Comment by jin521-qing** [comment]
非常感谢！！！这个问题已经解决啦，确实是环境问题，我直接导入 .yml文件总会报错~~但，我又有新的问题，sad，我还想再请教一下，    client: reverb.Client,   #original
AttributeError: module 'reverb' has no attribute 'Client'    ，然后我在python中使用 print(dir(reverb)) 打印出来reverb所有的属性，确实没有Client：>>> print(dir(reverb))
['Alphanum', 'Any', 'Char', 'DOTALL', 'Digit', 'Digits', 'End', 'EndString', 'FollowedBy', 'Group', 'IGNORECASE', 'LOCALE', 'MULTILINE', 'Match', 'Matched', 'Maybe', 'Optional', 'Raw', 'Re', 'Repeated', 'Required', 'Set', 'Start', 'StartString', 'Text', 'Whitespace', 'Wordbreak', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_ischar', '_prioritize', 're']  ，像这样情况怎么处理呢？我已经把reverb重新删了又下载，现在是2.0.1版本的，非常感谢，我真的超想把这个跑通呜呜呜

![image](https://user-images.githubusercontent.com/65586512/229296905-939438fc-6c8b-486b-b731-a1cc3a3f8826.png)

**Comment by neardws** [comment]
😂看样子你是安装错了，应该安装的是dm-reverb==0.7.0
```bash
pip install dm-reverb==0.7.0
```

还有类似问题，可以先查看 [environment.yml](https://github.com/neardws/Game-Theoretic-Deep-Reinforcement-Learning/blob/main/environment.yml)文件，直接搜索可以看见所需依赖的名字和版本。

当然，最方便的方式还是通过 ```bash conda env create -f environment.yml``` 安装，可以考虑下先解决导入 .yml文件报错问题。

**Comment by jin521-qing** [comment]
感谢感谢，终于动起来了呜呜呜

**Comment by neardws** [comment]
祝你顺利，如果还有运行环境问题，欢迎重开 issue。

**Comment by neardws** [comment]
祝你顺利，如果还有运行环境问题，欢迎重开 issue。

**Comment by wyt675** [comment]
![屏幕截图 2023-04-10 094007](https://user-images.githubusercontent.com/83149125/230808756-30d3f0df-0743-4479-b509-fdcd517c93be.png)
您好，我想问一下你是怎么解决这个问题的呀

**Comment by neardws** [comment]
可以提供更多信息吗？这个看不出是啥问题

**Comment by dyc-d** [comment]
> 

请问这个问题是如何解决的呢 我已经更换了protobuf的版本，还是不行

**Comment by jingluozzz** [comment]
> ![屏幕截图 2023-04-10 094007](https://user-images.githubusercontent.com/83149125/230808756-30d3f0df-0743-4479-b509-fdcd517c93be.png) 您好，我想问一下你是怎么解决这个问题的呀

您好，请问你这个问题解决了吗？

**Comment by wyt675** [comment]
没有，我后来没用linux了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月08日 20:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [neardws/Game-Theoretic-Deep-Reinforcement-Learning] libserialization_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv (Issue #8) |

您好，我想问一下你是怎么解决这个问题的呀

您好，请问你这个问题解决了吗？

**Comment by jingluozzz** [comment]
换windows跑通了吗？这个问题，csdn上都没啥具体解决方法，改的头都大了

**Comment by jingluozzz** [comment]
> 没有，我后来没用linux了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年01月08日 20:25 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [neardws/Game-Theoretic-Deep-Reinforcement-Learning] libserialization_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv (Issue #8) | 您好，我想问一下你是怎么解决这个问题的呀 您好，请问你这个问题解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

换windows跑通了吗？这个问题，csdn上都没啥具体解决方法，改的头都大了

**Comment by wyt675** [comment]
没有使用windows跑作者的代码，使用了作者代码的一些思路



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月08日 22:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [neardws/Game-Theoretic-Deep-Reinforcement-Learning] libserialization_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv (Issue #8) |

没有，我后来没用linux了
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年01月08日 20:25 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [neardws/Game-Theoretic-Deep-Reinforcement-Learning] libserialization_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv (Issue #8) | 您好，我想问一下你是怎么解决这个问题的呀 您好，请问你这个问题解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

换windows跑通了吗？这个问题，csdn上都没啥具体解决方法，改的头都大了

**Comment by jingluozzz** [comment]
> ![image](https://user-images.githubusercontent.com/65586512/229057103-8bce57ca-e438-458d-b16f-1601bae99952.png) 您好，请问这个问题是因为啥？我查到可能是版本问题，我安装了protobuf3.17.2 ,也不可以，请问您使用的是啥版本？或许有其他解决办法吗？非常感谢🙇‍

师姐您好，我想问一下关于libserialization_cc_proto.so: undefined symbol:_ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev这个报错怎么解决的，protobuf==3.20.1和protobuf==3.20.0这两个版本我都下载过，但依旧报同样的错误，实在不清楚是哪里的问题，您方便说一下您是如何解决的吗？ @jin521-qing

**Comment by wyt00001** [comment]
您好，请问有人见过这个问题吗
ImportError: /usr/local/anaconda3/lib/python3.9/site-packages/courier/python/libserialization_cc_proto.so: undefined symbol: scc_info_TensorProto_tensorflow_2fcore_2fframework_2ftensor_2eproto

**Comment by wyt00001** [comment]
您好，请问如何解决这个问题
ImportError: /usr/local/anaconda3/lib/python3.9/site-packages/courier/python/libserialization_cc_proto.so: undefined symbol: scc_info_TensorProto_tensorflow_2fcore_2fframework_2ftensor_2eproto
